name: 🔰 Build por push
run-name: 🚀 Ação disparada por ${{ github.actor }} 💥

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      # - name: Configurar Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "14" 

      - name: Instalando dependências
        run: yarn

      - name: Realizando build da aplicação
        run: yarn build

      - name: Fazer upload da pasta dist para o repositório
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: dist

      - name: Enviar arquivo para o servidor Ubuntu 🚀🚀
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/app"
          EXCLUDE: "/dist/, /node_modules/"